export type PortalCatalogMode = 'cards' | 'list' | 'magazine' | 'datatable';
export type PortalHeroMode = 'classic' | 'split' | 'editorial' | 'search' | 'compact' | 'showcase';

export interface PortalTemplate {
  id: string;
  name: string;
  inspiration: string;
  premiumUse: string;
  heroMode: PortalHeroMode;
  catalogMode: PortalCatalogMode;
  shell: string;
  header: string;
  hero: string;
  heroPanel: string;
  filterPanel: string;
  card: string;
  cardImage: string;
  accentLabel: string;
}

const darkHeader = 'border-white/10 bg-[#0b111f]/92 backdrop-blur-xl';
const lightHeader = 'border-slate-200 bg-white/92 backdrop-blur-xl';

export const PORTAL_TEMPLATES: PortalTemplate[] = [
  {
    id: 'classico-premium',
    name: 'Clássico Premium',
    inspiration: 'Portal atual Socimob',
    premiumUse: 'Imobiliárias generalistas com acervo variado',
    heroMode: 'classic',
    catalogMode: 'cards',
    shell: '#f4efe8',
    header: darkHeader,
    hero: 'linear-gradient(115deg, var(--portal-primary-99) 0%, #0a0d1678 100%)',
    heroPanel: 'rounded-[1.75rem] border border-white/30 bg-[#000000c2] p-5 backdrop-blur-[8px] shadow-[0_20px_60px_rgba(0,0,0,0.28)] md:p-8',
    filterPanel: 'rounded-3xl border border-black/10 bg-white/80 p-4 backdrop-blur-md shadow-[0_16px_42px_rgba(15,23,42,0.10)] lg:p-5',
    card: 'overflow-hidden rounded-2xl border border-black/10 bg-white shadow-[0_10px_26px_rgba(15,23,42,0.08)]',
    cardImage: 'h-60 sm:h-52',
    accentLabel: 'Curadoria imobiliária premium',
  },
  {
    id: 'manhattan-signature',
    name: 'Manhattan Signature',
    inspiration: 'Corcoran, Compass e SERHANT',
    premiumUse: 'Apartamentos urbanos, alto padrão e lançamentos',
    heroMode: 'split',
    catalogMode: 'cards',
    shell: '#f6f7f8',
    header: lightHeader,
    hero: 'linear-gradient(115deg, #111827 0%, #263241 100%)',
    heroPanel: 'border-l-4 border-white/80 bg-white/95 p-6 shadow-[0_24px_70px_rgba(15,23,42,0.18)] md:p-9',
    filterPanel: 'border-y border-slate-200 bg-white p-4 shadow-[0_10px_28px_rgba(15,23,42,0.06)] lg:p-5',
    card: 'overflow-hidden border border-slate-200 bg-white shadow-[0_8px_24px_rgba(15,23,42,0.06)]',
    cardImage: 'h-72 sm:h-60',
    accentLabel: 'Residências urbanas selecionadas',
  },
  {
    id: 'riviera-resort',
    name: 'Riviera Resort',
    inspiration: 'Sotheby’s Realty e Costa del Sol',
    premiumUse: 'Casas de praia, segunda residência e imóveis com lazer',
    heroMode: 'showcase',
    catalogMode: 'magazine',
    shell: '#eef7f6',
    header: 'border-white/15 bg-[#073b3a]/90 backdrop-blur-xl',
    hero: 'linear-gradient(120deg, #073b3a 0%, #0e7490 100%)',
    heroPanel: 'rounded-2xl border border-white/25 bg-white/14 p-6 text-white backdrop-blur-md shadow-[0_24px_70px_rgba(8,47,73,0.25)] md:p-9',
    filterPanel: 'rounded-2xl border border-cyan-100 bg-white p-4 shadow-[0_14px_36px_rgba(14,116,144,0.11)] lg:p-5',
    card: 'overflow-hidden rounded-[1.25rem] border border-cyan-100 bg-white shadow-[0_10px_28px_rgba(14,116,144,0.10)]',
    cardImage: 'h-72 sm:h-64',
    accentLabel: 'Viver com vista e respiro',
  },
  {
    id: 'london-editorial',
    name: 'London Editorial',
    inspiration: 'Knight Frank e Savills',
    premiumUse: 'Imóveis tradicionais, corporativos e bairros nobres',
    heroMode: 'editorial',
    catalogMode: 'list',
    shell: '#f7f5f1',
    header: lightHeader,
    hero: 'linear-gradient(120deg, #241f1a 0%, #5b4b3d 100%)',
    heroPanel: 'border-y border-white/40 bg-[#241f1acc] p-6 md:p-9',
    filterPanel: 'border border-stone-200 bg-[#fffdf8] p-4 shadow-[0_10px_28px_rgba(68,64,60,0.08)] lg:p-5',
    card: 'overflow-hidden border-b border-stone-200 bg-[#fffdf8]',
    cardImage: 'h-64 sm:h-52',
    accentLabel: 'Propriedades com curadoria editorial',
  },
  {
    id: 'dubai-skyline',
    name: 'Dubai Skyline',
    inspiration: 'Emaar e LuxuryProperty.com',
    premiumUse: 'Lançamentos, torres, investidores e imóveis aspiracionais',
    heroMode: 'split',
    catalogMode: 'cards',
    shell: '#f5f7fb',
    header: 'border-white/10 bg-[#08111f]/94 backdrop-blur-xl',
    hero: 'linear-gradient(125deg, #08111f 0%, #123456 62%, #c7a45d 100%)',
    heroPanel: 'rounded-xl border border-[#c7a45d]/55 bg-[#08111fcc] p-6 shadow-[0_24px_80px_rgba(8,17,31,0.45)] md:p-9',
    filterPanel: 'rounded-xl border border-[#c7a45d]/25 bg-white p-4 shadow-[0_16px_40px_rgba(8,17,31,0.12)] lg:p-5',
    card: 'overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_14px_34px_rgba(8,17,31,0.10)]',
    cardImage: 'h-64 sm:h-56',
    accentLabel: 'Lançamentos e oportunidades premium',
  },
  {
    id: 'scandinavian-minimal',
    name: 'Scandinavian Minimal',
    inspiration: 'Hemnet e portals nórdicos',
    premiumUse: 'Catálogo limpo para fotos claras e imóveis compactos',
    heroMode: 'compact',
    catalogMode: 'cards',
    shell: '#f8fafc',
    header: lightHeader,
    hero: 'linear-gradient(120deg, #e2e8f0 0%, #ffffff 100%)',
    heroPanel: 'bg-white p-6 shadow-[0_10px_30px_rgba(15,23,42,0.08)] md:p-9',
    filterPanel: 'border border-slate-200 bg-white p-4 lg:p-5',
    card: 'overflow-hidden border border-slate-200 bg-white',
    cardImage: 'h-60 sm:h-52',
    accentLabel: 'Design limpo, busca objetiva',
  },
  {
    id: 'tokyo-compact',
    name: 'Tokyo Compact',
    inspiration: 'SUUMO e Homes Japan',
    premiumUse: 'Muitos imóveis, leitura rápida e ficha técnica forte',
    heroMode: 'search',
    catalogMode: 'list',
    shell: '#f3f6f9',
    header: lightHeader,
    hero: 'linear-gradient(120deg, #152238 0%, #31425f 100%)',
    heroPanel: 'rounded-lg border border-white/20 bg-white/95 p-5 shadow-[0_18px_48px_rgba(15,34,56,0.22)] md:p-7',
    filterPanel: 'rounded-lg border border-slate-200 bg-white p-4 shadow-[0_10px_26px_rgba(15,34,56,0.08)] lg:p-5',
    card: 'overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm',
    cardImage: 'h-52 sm:h-44',
    accentLabel: 'Busca rápida com dados completos',
  },
  {
    id: 'paris-boutique',
    name: 'Paris Boutique',
    inspiration: 'Barnes e Daniel Féau',
    premiumUse: 'Imóveis de charme, boutique e alto padrão clássico',
    heroMode: 'editorial',
    catalogMode: 'magazine',
    shell: '#fbf7f3',
    header: lightHeader,
    hero: 'linear-gradient(120deg, #3b2f2f 0%, #8d6e63 100%)',
    heroPanel: 'rounded-t-[2rem] border border-white/35 bg-[#fff8f0e8] p-6 shadow-[0_20px_60px_rgba(59,47,47,0.22)] md:p-9',
    filterPanel: 'rounded-t-[2rem] border border-rose-100 bg-white p-4 shadow-[0_12px_32px_rgba(59,47,47,0.08)] lg:p-5',
    card: 'overflow-hidden rounded-t-[1.5rem] border border-rose-100 bg-white shadow-[0_10px_28px_rgba(59,47,47,0.08)]',
    cardImage: 'h-72 sm:h-60',
    accentLabel: 'Seleção boutique de endereços especiais',
  },
  {
    id: 'lisbon-heritage',
    name: 'Lisbon Heritage',
    inspiration: 'Idealista Portugal e JLL Portugal',
    premiumUse: 'Casas históricas, bairros residenciais e turismo residencial',
    heroMode: 'classic',
    catalogMode: 'cards',
    shell: '#f7f3ec',
    header: 'border-white/12 bg-[#1f2933]/92 backdrop-blur-xl',
    hero: 'linear-gradient(120deg, #1f2933 0%, #7c6a46 100%)',
    heroPanel: 'rounded-xl border border-white/30 bg-[#1f2933d6] p-6 shadow-[0_18px_54px_rgba(31,41,51,0.30)] md:p-9',
    filterPanel: 'rounded-xl border border-stone-200 bg-white p-4 shadow-[0_12px_32px_rgba(31,41,51,0.09)] lg:p-5',
    card: 'overflow-hidden rounded-xl border border-stone-200 bg-white shadow-[0_10px_28px_rgba(31,41,51,0.08)]',
    cardImage: 'h-64 sm:h-56',
    accentLabel: 'Tradição, localização e valor patrimonial',
  },
  {
    id: 'miami-waterfront',
    name: 'Miami Waterfront',
    inspiration: 'The Agency e waterfront brokers',
    premiumUse: 'Frente mar, lifestyle, piscinas e condomínios clube',
    heroMode: 'showcase',
    catalogMode: 'magazine',
    shell: '#eef9fb',
    header: 'border-white/15 bg-[#06202b]/91 backdrop-blur-xl',
    hero: 'linear-gradient(120deg, #06202b 0%, #00a6a6 100%)',
    heroPanel: 'rounded-[1.5rem] border border-white/30 bg-[#06202bd6] p-6 shadow-[0_24px_70px_rgba(6,32,43,0.35)] md:p-9',
    filterPanel: 'rounded-[1.5rem] border border-teal-100 bg-white p-4 shadow-[0_16px_40px_rgba(6,95,70,0.10)] lg:p-5',
    card: 'overflow-hidden rounded-[1.5rem] border border-teal-100 bg-white shadow-[0_14px_36px_rgba(6,95,70,0.10)]',
    cardImage: 'h-72 sm:h-64',
    accentLabel: 'Waterfront living e imóveis de lazer',
  },
  {
    id: 'zurich-private',
    name: 'Zurich Private',
    inspiration: 'Properstar e consultorias suíças',
    premiumUse: 'Clientes discretos, luxo silencioso e imóveis exclusivos',
    heroMode: 'compact',
    catalogMode: 'list',
    shell: '#f5f5f4',
    header: lightHeader,
    hero: 'linear-gradient(120deg, #18181b 0%, #3f3f46 100%)',
    heroPanel: 'border border-zinc-300 bg-white p-6 shadow-[0_14px_40px_rgba(24,24,27,0.12)] md:p-9',
    filterPanel: 'border border-zinc-200 bg-white p-4 lg:p-5',
    card: 'overflow-hidden border border-zinc-200 bg-white shadow-[0_8px_22px_rgba(24,24,27,0.06)]',
    cardImage: 'h-56 sm:h-48',
    accentLabel: 'Luxo discreto, seleção privada',
  },
  {
    id: 'sao-paulo-corporate',
    name: 'São Paulo Corporate',
    inspiration: 'Lopes, Loft e portais urbanos BR',
    premiumUse: 'Imóveis urbanos, comerciais e compra recorrente',
    heroMode: 'search',
    catalogMode: 'list',
    shell: '#f1f5f9',
    header: 'border-slate-200 bg-white/94 backdrop-blur-xl',
    hero: 'linear-gradient(120deg, #0f172a 0%, #334155 100%)',
    heroPanel: 'rounded-lg border border-white/20 bg-white p-5 shadow-[0_18px_48px_rgba(15,23,42,0.18)] md:p-7',
    filterPanel: 'rounded-lg border border-slate-200 bg-white p-4 shadow-sm lg:p-5',
    card: 'overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm',
    cardImage: 'h-52 sm:h-44',
    accentLabel: 'Catálogo urbano de alta conversão',
  },
  {
    id: 'madrid-marketplace',
    name: 'Madrid Marketplace',
    inspiration: 'Idealista Espanha e Fotocasa',
    premiumUse: 'Alto volume com filtros objetivos e cards densos',
    heroMode: 'search',
    catalogMode: 'cards',
    shell: '#fffaf0',
    header: 'border-amber-200 bg-white/94 backdrop-blur-xl',
    hero: 'linear-gradient(120deg, #7c2d12 0%, #d97706 100%)',
    heroPanel: 'rounded-xl border border-white/25 bg-white p-5 shadow-[0_18px_48px_rgba(124,45,18,0.20)] md:p-7',
    filterPanel: 'rounded-xl border border-amber-200 bg-white p-4 shadow-[0_12px_28px_rgba(180,83,9,0.10)] lg:p-5',
    card: 'overflow-hidden rounded-xl border border-amber-100 bg-white shadow-[0_10px_24px_rgba(180,83,9,0.08)]',
    cardImage: 'h-56 sm:h-48',
    accentLabel: 'Busca direta para grande inventário',
  },
  {
    id: 'berlin-gallery',
    name: 'Berlin Gallery',
    inspiration: 'Engel & Völkers e design editorial europeu',
    premiumUse: 'Fotos autorais, arquitetura e imóveis de design',
    heroMode: 'editorial',
    catalogMode: 'magazine',
    shell: '#f8fafc',
    header: 'border-white/10 bg-black/88 backdrop-blur-xl',
    hero: 'linear-gradient(120deg, #000000 0%, #374151 100%)',
    heroPanel: 'border border-white/20 bg-black/70 p-6 shadow-[0_24px_70px_rgba(0,0,0,0.35)] md:p-9',
    filterPanel: 'border border-slate-200 bg-white p-4 shadow-[0_12px_32px_rgba(0,0,0,0.06)] lg:p-5',
    card: 'overflow-hidden border border-slate-200 bg-white shadow-[0_12px_30px_rgba(0,0,0,0.07)]',
    cardImage: 'h-80 sm:h-72',
    accentLabel: 'Arquitetura, imagem e presença',
  },
  {
    id: 'singapore-smart',
    name: 'Singapore Smart',
    inspiration: 'PropertyGuru e 99.co',
    premiumUse: 'Condomínios, comparativo rápido e leads mobile',
    heroMode: 'search',
    catalogMode: 'cards',
    shell: '#f4f7fb',
    header: 'border-slate-200 bg-white/94 backdrop-blur-xl',
    hero: 'linear-gradient(120deg, #111827 0%, #1d4ed8 100%)',
    heroPanel: 'rounded-2xl border border-white/20 bg-white p-5 shadow-[0_18px_48px_rgba(29,78,216,0.16)] md:p-7',
    filterPanel: 'rounded-2xl border border-blue-100 bg-white p-4 shadow-[0_12px_32px_rgba(29,78,216,0.08)] lg:p-5',
    card: 'overflow-hidden rounded-2xl border border-blue-100 bg-white shadow-[0_10px_28px_rgba(29,78,216,0.07)]',
    cardImage: 'h-56 sm:h-48',
    accentLabel: 'Decisão rápida, dados claros',
  },
  {
    id: 'cape-town-villa',
    name: 'Cape Town Villa',
    inspiration: 'Luxury Africa e villas costeiras',
    premiumUse: 'Casas amplas, terrenos, vista e lifestyle familiar',
    heroMode: 'showcase',
    catalogMode: 'magazine',
    shell: '#f6f4ef',
    header: 'border-white/10 bg-[#18220f]/90 backdrop-blur-xl',
    hero: 'linear-gradient(120deg, #18220f 0%, #556b2f 100%)',
    heroPanel: 'rounded-[1.75rem] border border-white/25 bg-[#18220fd6] p-6 shadow-[0_22px_64px_rgba(24,34,15,0.32)] md:p-9',
    filterPanel: 'rounded-[1.75rem] border border-lime-100 bg-white p-4 shadow-[0_14px_36px_rgba(63,98,18,0.10)] lg:p-5',
    card: 'overflow-hidden rounded-[1.75rem] border border-lime-100 bg-white shadow-[0_12px_32px_rgba(63,98,18,0.10)]',
    cardImage: 'h-80 sm:h-64',
    accentLabel: 'Villas, terrenos e natureza urbana',
  },
  {
    id: 'toronto-family',
    name: 'Toronto Family',
    inspiration: 'RE/MAX, Realtor.ca e Royal LePage',
    premiumUse: 'Famílias, bairros, casas e filtros práticos',
    heroMode: 'split',
    catalogMode: 'cards',
    shell: '#f7fafc',
    header: lightHeader,
    hero: 'linear-gradient(120deg, #1e3a5f 0%, #64748b 100%)',
    heroPanel: 'rounded-xl border border-white/25 bg-white p-6 shadow-[0_18px_48px_rgba(30,58,95,0.18)] md:p-8',
    filterPanel: 'rounded-xl border border-slate-200 bg-white p-4 shadow-[0_10px_26px_rgba(30,58,95,0.08)] lg:p-5',
    card: 'overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_10px_26px_rgba(30,58,95,0.08)]',
    cardImage: 'h-60 sm:h-52',
    accentLabel: 'Casas para o próximo capítulo',
  },
  {
    id: 'bali-retreat',
    name: 'Bali Retreat',
    inspiration: 'Villas tropicais e hospitality real estate',
    premiumUse: 'Imóveis de temporada, retiros, pousadas e lazer',
    heroMode: 'showcase',
    catalogMode: 'magazine',
    shell: '#f4fbf6',
    header: 'border-white/12 bg-[#123524]/90 backdrop-blur-xl',
    hero: 'linear-gradient(120deg, #123524 0%, #2f855a 100%)',
    heroPanel: 'rounded-[2rem] border border-white/25 bg-[#123524d6] p-6 shadow-[0_24px_70px_rgba(18,53,36,0.34)] md:p-9',
    filterPanel: 'rounded-[2rem] border border-emerald-100 bg-white p-4 shadow-[0_14px_36px_rgba(22,101,52,0.10)] lg:p-5',
    card: 'overflow-hidden rounded-[2rem] border border-emerald-100 bg-white shadow-[0_12px_32px_rgba(22,101,52,0.10)]',
    cardImage: 'h-80 sm:h-64',
    accentLabel: 'Refúgios, renda e experiência',
  },
  {
    id: 'data-room-investor',
    name: 'Data Room Investor',
    inspiration: 'CREXi, LoopNet e dashboards de investimento',
    premiumUse: 'Investidores, imóveis comerciais e comparação por tabela',
    heroMode: 'compact',
    catalogMode: 'datatable',
    shell: '#f8fafc',
    header: 'border-slate-200 bg-white/95 backdrop-blur-xl',
    hero: 'linear-gradient(120deg, #111827 0%, #374151 100%)',
    heroPanel: 'rounded-lg border border-slate-200 bg-white p-5 shadow-[0_16px_42px_rgba(15,23,42,0.12)] md:p-7',
    filterPanel: 'rounded-lg border border-slate-200 bg-white p-4 shadow-sm lg:p-5',
    card: 'overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm',
    cardImage: 'h-48 sm:h-40',
    accentLabel: 'Data room de oportunidades',
  },
  {
    id: 'ultra-luxury-black',
    name: 'Ultra Luxury Black',
    inspiration: 'Christie’s International Real Estate',
    premiumUse: 'Mansões, imóveis ultra premium e apresentação exclusiva',
    heroMode: 'editorial',
    catalogMode: 'magazine',
    shell: '#080808',
    header: 'border-white/10 bg-black/94 backdrop-blur-xl',
    hero: 'linear-gradient(120deg, #000000 0%, #161616 100%)',
    heroPanel: 'rounded-none border border-white/15 bg-black/78 p-6 shadow-[0_24px_80px_rgba(0,0,0,0.55)] md:p-10',
    filterPanel: 'border border-white/10 bg-[#111] p-4 shadow-[0_18px_50px_rgba(0,0,0,0.30)] lg:p-5',
    card: 'overflow-hidden border border-white/10 bg-[#111] shadow-[0_18px_42px_rgba(0,0,0,0.28)]',
    cardImage: 'h-80 sm:h-72',
    accentLabel: 'Coleção privada ultra premium',
  },
];

export const DEFAULT_PORTAL_TEMPLATE_ID = 'classico-premium';

export function getPortalTemplate(id?: string | null): PortalTemplate {
  return PORTAL_TEMPLATES.find((template) => template.id === id) || PORTAL_TEMPLATES[0];
}
